### ISSUE TITLE
Help, can't get work

### ISSUE THREAD

**Issue by torcheQ** [robro/combomake#1]
Hello, Could you please explain more in the Readme file ?
I can't figure out where to put the combo like "2m m jH" etc...
I edit the template file and put the combo between
; BEGIN COMBO
; END COMBO
But when I launch the template with AHK it say : Error this line does not contain a recognized action.
Maybe I doesn't understand your program ahah
Sorry for my english :/
And thank you for your work !

**Comment by robro** [comment]
Sorry, I should have put more detail in the readme. Perhaps a quick tutorial explaining the typical workflow. The main thing is that combomake.py looks for a text file from which to read. I use "filename.combo" but the extension doesn't matter; it can be whatever you want.

So let's say in the same folder as combomake you make a text file called "goku_bnb.combo" inside which is the text:

`goku 2m 5m jcf jmll j2h sd jmll j2h djlll`

Then from a command line you would navigate to that folder and enter:

`./combomake.py goku_bnb.combo`

After which you should see some output in the console confirming that the AHK file was successfully generated.

You should then be able to open that file with AHK and execute the combo in-game. The default key combination is Ctrl+Alt+Z but you can change that in the template file or the individual generated AHK file. To kill the combo during execution if something goes wrong hit Esc.

**Comment by ljara2106** [comment]
Can you do like a small video tutorial please, not able to make it work, keep getting error.

**Comment by robro** [comment]
Can you elaborate on what error you're getting and describe what you did to make it happen?

**Comment by ljara2106** [comment]
see attached.
![PrtScr capture](https://user-images.githubusercontent.com/20650464/56871493-b0bebf80-69ec-11e9-832f-d401b07587d9.jpg)

**Comment by ljara2106** [comment]
i basically copied and pasted your line from your comment from last year into the .combo file.

**Comment by robro** [comment]
I see. I didn't realize you were using cmd.exe. I usually use Bash in which the '.' syntax is supported. In cmd you would instead use:
`python combomake.py goku_bnb.combo`

Let me know if that works.

**Comment by robro** [comment]
Also, this script was written for Python 2.7 and that other error in your screenshot would suggest you're probably using Python 3.x. If you enter:
`python --version`

What does it say?

**Comment by ljara2106** [comment]
correct im using 3.7.0

**Comment by robro** [comment]
Alright, since it was easy, I just pushed an update that fixes the print statements to work with Python 3. Let me know if it works now.

**Comment by ljara2106** [comment]
it works now with new code- thanks.

**Comment by robro** [comment]
Great. One thing to note is that some timing data has become outdated due to patches since I made this. So, some things might just not work. I haven't had the time to update it, but feel free to adjust things if need be.
